live_config_reload = true

[colors.primary]
background = '#000b1e'
#foreground = '#0abdc6'
#foreground = '#baf6ff'
foreground = '#00ffff'

[colors.cursor]
text   = '#000b1e'
cursor = '#0abdc6'

# Normal colors
[colors.normal]
black   = '#123e7c'
red     = '#ff0000'
green   = '#21f500'
yellow  = '#f3e600'
blue    = '#003ec4'
magenta = '#642fde'
cyan    = '#0abdc6'
white   = '#d7d7d5'

# Bright colors
[colors.bright]
black   = '#1c61c2'
red     = '#ff0073'
green   = '#00ff00'
yellow  = '#f57800'
blue    = '#00aaef'
magenta = '#611cef'
cyan    = '#0ffbff'
white   = '#d7d7d5'

# import = [
    #"~/.config/alacritty/themes/themes/cyber_punk_neon.toml"
	#"~/.config/alacritty/themes/themes/tokyo-night.toml"
# ]

[cursor]
style = "Underline"


[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.8

option_as_alt = "Both"

[window.padding]
x = 20
y = 20


[font]
normal.family = "Hack Nerd Font Mono"

size = 14
